# Generated by Django 4.2 on 2025-09-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
